# Generated by Django 4.1 on 2023-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('MobileNo', models.CharField(max_length=40)),
                ('Class', models.CharField(max_length=30)),
                ('Batch', models.TextField()),
                ('Coupon', models.TextField()),
            ],
        ),
    ]
