# Generated by Django 4.1 on 2023-01-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_classrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrecord',
            name='Time',
        ),
    ]
