# Generated by Django 4.1 on 2023-01-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_classrecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='Time',
            field=models.DateField(default=0),
        ),
    ]
