# Generated by Django 4.1 on 2023-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_staffattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='Date',
            field=models.DateField(),
        ),
    ]
