# Generated by Django 4.1 on 2023-01-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_topper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('School', models.CharField(max_length=300)),
            ],
        ),
    ]
