# Generated by Django 4.1 on 2023-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_class1'),
    ]

    operations = [
        migrations.CreateModel(
            name='igallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=400)),
                ('gpic', models.ImageField(default='', upload_to='static/gallery/')),
            ],
        ),
    ]
