# Generated by Django 4.1 on 2023-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='Amount',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary',
            field=models.IntegerField(max_length=10),
        ),
    ]
