# Generated by Django 4.1 on 2023-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_salary_amount_alter_salary_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='videonews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.CharField(max_length=500)),
                ('vhead', models.CharField(max_length=500)),
                ('vdate', models.DateField()),
            ],
        ),
    ]
