# Generated by Django 4.1 on 2023-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_videonews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=500)),
                ('vdate', models.DateField()),
            ],
        ),
    ]
